// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2hp5ZAvRNQ0rNJubkoSET9nCUgrIA0zk',
    appId: '1:762523826099:web:4551e394c1bf78fdc4fdc6',
    messagingSenderId: '762523826099',
    projectId: 'nomnom-safe',
    authDomain: 'nomnom-safe.firebaseapp.com',
    storageBucket: 'nomnom-safe.firebasestorage.app',
    measurementId: 'G-G9SELLSV4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiAs3rgf6Kl7gYFXs6PG2WCk5z_3Z-r3s',
    appId: '1:762523826099:android:97707fa7fb3b4525c4fdc6',
    messagingSenderId: '762523826099',
    projectId: 'nomnom-safe',
    storageBucket: 'nomnom-safe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCghPc53FNxe6JIXT11sfT8ZZ1V49zjfHY',
    appId: '1:762523826099:ios:9d096e6689ef4b5cc4fdc6',
    messagingSenderId: '762523826099',
    projectId: 'nomnom-safe',
    storageBucket: 'nomnom-safe.firebasestorage.app',
    iosBundleId: 'com.example.nomnomSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCghPc53FNxe6JIXT11sfT8ZZ1V49zjfHY',
    appId: '1:762523826099:ios:9d096e6689ef4b5cc4fdc6',
    messagingSenderId: '762523826099',
    projectId: 'nomnom-safe',
    storageBucket: 'nomnom-safe.firebasestorage.app',
    iosBundleId: 'com.example.nomnomSafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2hp5ZAvRNQ0rNJubkoSET9nCUgrIA0zk',
    appId: '1:762523826099:web:15f1275c9878acd3c4fdc6',
    messagingSenderId: '762523826099',
    projectId: 'nomnom-safe',
    authDomain: 'nomnom-safe.firebaseapp.com',
    storageBucket: 'nomnom-safe.firebasestorage.app',
    measurementId: 'G-4W5NVMQM3K',
  );
}
